apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
    app: nginx
spec:
  containers:
  - name: nginx-pod
    image: nginx:1.14.2
    ports:
      - containerPort: 8080